name: deploy
on:
  push:
    branches: [ "main" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: cd server_monitoring && docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: clone
        run: git clone https://github.com/IgorKolotushkin/server_monitoring.git
      - name: docker-compose
        run: cd server_monitoring && docker-compose up --build -d
